server:
  port: 8081

##################### SPRING GLOBAL #################################
spring:
  ##################### DATA SOURCE #################################
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    ##################### MY SQL DATABASE #################################
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: testing321

  # custom configuration via Configuration files
kafka:
  general:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  orders:
    group-id: ${GROUP_ID:objects-group}
    topic: ${KAFKA_DEFAULT_TOPIC:domain-orders-topic}

message:
  processing:
    time: 0