##################### SPRING GLOBAL #################################
spring:
  ##################### DATA SOURCE #################################
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    ##################### MY SQL DATABASE #################################
    url: jdbc:postgresql://localhost:5432/dlib
    username: postgres
    password: testing321